apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: baremetal-operator-system
---
apiVersion: v1
data:
  CACHEURL: http://172.22.0.1/images
  DEPLOY_KERNEL_URL: http://172.22.0.2:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://172.22.0.2:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: 172.22.0.10,172.22.0.100
  HTTP_PORT: "6180"
  INSPECTOR_REVERSE_PROXY_SETUP: "false"
  IRONIC_ENDPOINT: http://172.22.0.2:6385/v1/
  IRONIC_FAST_TRACK: "true"
  IRONIC_INSPECTOR_ENDPOINT: http://172.22.0.2:5050/v1/
  IRONIC_KERNEL_PARAMS: console=ttyS0
  LISTEN_ALL_INTERFACES: '"false"'
  PROVISIONING_CIDR: "24"
  PROVISIONING_INTERFACE: ironicendpoint
  PROVISIONING_IP: 172.22.0.1
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
  namespace: baremetal-operator-system
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: baremetal-operator-mariadb-password-ftkgc8tmkc
  namespace: baremetal-operator-system
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-ironic
  namespace: baremetal-operator-system
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      name: ironic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ironic
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/keepalived
        name: ironic-endpoint-keepalived
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      - command:
        - /bin/rundnsmasq
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - ss -lun | grep :67 && ss -lun | grep :69
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: ironic-dnsmasq
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - ss -lun | grep :67 && ss -lun | grep :69
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: baremetal-operator-mariadb-password-ftkgc8tmkc
        - name: RESTART_CONTAINER_CERTIFICATE_UPDATED
          valueFrom:
            configMapKeyRef:
              key: RESTART_CONTAINER_CERTIFICATE_UPDATED
              name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/mariadb
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin status -uironic -p$(printenv MARIADB_PASSWORD)
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: mariadb
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin status -uironic -p$(printenv MARIADB_PASSWORD)
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: baremetal-operator-mariadb-password-ftkgc8tmkc
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sSf http://127.0.0.1:6385 || curl -sSfk https://127.0.0.1:6385
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: ironic
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sSf http://127.0.0.1:6385 || curl -sSfk https://127.0.0.1:6385
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runlogwatch.sh
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        name: ironic-log-watch
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic-inspector
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sSf http://127.0.0.1:5050 || curl -sSf -k https://127.0.0.1:5050
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: ironic-inspector
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sSf http://127.0.0.1:5050 || curl -sSf -k https://127.0.0.1:5050
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      - command:
        - /bin/runhttpd
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/ironic
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sSfk https://127.0.0.1:6180
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: ironic-httpd
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sSfk https://127.0.0.1:6180
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      hostNetwork: true
      initContainers:
      - command:
        - /usr/local/bin/get-resource.sh
        envFrom:
        - configMapRef:
            name: baremetal-operator-ironic-bmo-configmap-kf5k84ff8c
        image: quay.io/metal3-io/ironic-ipa-downloader
        imagePullPolicy: Always
        name: ironic-ipa-downloader
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      volumes:
      - emptyDir: {}
        name: ironic-data-volume
